---
name: ci_root_ancestor_for_pipeline_family
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/46575 
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/287812 
milestone: '13.7'
type: development
group: group::continuous integration
default_enabled: false
